package com.dao;

public class Queries
{
	public static String USERS_SQL = "select count(*) from users where USER_NAME=? and USER_PASS=?";
	public static String GET_CLASSES = "SELECT CLASS_ID, CLASS_NAME FROM CLASSES";
	public static String GET_STUDENTS = "SELECT STUD_ID, STUD_NAME FROM STUDENTS";
	public static String GET_TEACHERS = "SELECT TEACHER_ID, TEACHER_NAME FROM TEACHERS";
	public static String GET_SUBJECTS = "SELECT SUB_ID, SUB_NAME FROM SUBJECTS";
	public static String UPDATE_STUDENTS = "UPDATE STUDENTS SET CLASS_ID=? WHERE STUD_ID=?";
	public static String GET_STUDENTS_AND_CLASSES = "SELECT STUD_ID, CLASS_ID FROM STUDENTS WHERE CLASS_ID IS NOT NULL";
	public static String CLASS_TEACH_SUB = "INSERT INTO CLASS_TEACH_SUB(CLASS_ID, TEACHER_ID, SUB_ID) VALUES (?, ?, ?)";
	public static String GET_CLASS_TEACH_SUB = "SELECT CTS_ID, CLASS_NAME, TEACHER_NAME, SUB_ID FROM CLASS_TEACH_SUB cts, CLASSES cl, TEACHERS t WHERE cl.CLASS_ID = cts.CLASS_ID AND t.TEACHER_ID = cts.TEACHER_ID";
	public static String GET_CLASS_STUD = "SELECT CLASS_NAME, STUD_NAME FROM CLASSES cl, STUDENTS s WHERE cl.CLASS_ID = s.CLASS_ID";
	public static String ADD_STUDENT = "INSERT INTO STUDENTS(STUD_NAME) VALUES(?)";
	public static String ADD_TEACHER = "INSERT INTO TEACHERS(TEACHER_NAME) VALUES(?)";
}
