DROP TABLE SUBJECTS;
DROP TABLE TEACHERS;
DROP TABLE CLASSES;
DROP TABLE STUDENTS;
DROP TABLE CLASS_TEACH_SUB;
DROP TABLE USERS;


CREATE TABLE SUBJECTS
(
	SUB_ID int NOT NULL auto_increment,
    PRIMARY KEY(SUB_ID),
	SUB_NAME VARCHAR(20) NOT NULL
)
auto_increment=1001;

INSERT INTO SUBJECTS(SUB_NAME) VALUES('HISTORY');
INSERT INTO SUBJECTS(SUB_NAME) VALUES('MATHS');
INSERT INTO SUBJECTS(SUB_NAME) VALUES('SCIENCE');
INSERT INTO SUBJECTS(SUB_NAME) VALUES('GEOGRAPHY');
INSERT INTO SUBJECTS(SUB_NAME) VALUES('ENGLISH');
INSERT INTO SUBJECTS(SUB_NAME) VALUES('HINDI');
INSERT INTO SUBJECTS(SUB_NAME) VALUES('MARATHI');
INSERT INTO SUBJECTS(SUB_NAME) VALUES('COMPUTERS');

CREATE TABLE TEACHERS
(
	TEACHER_ID int NOT NULL auto_increment,
    PRIMARY KEY(TEACHER_ID),
	TEACHER_NAME VARCHAR(25) NOT NULL
)
auto_increment=2001;

INSERT INTO TEACHERS(TEACHER_NAME) VALUES('MEGHA');
INSERT INTO TEACHERS(TEACHER_NAME) VALUES('ASHOK');
INSERT INTO TEACHERS(TEACHER_NAME) VALUES('DINESH');
INSERT INTO TEACHERS(TEACHER_NAME) VALUES('KISHOR');

CREATE TABLE CLASSES
(
	CLASS_ID int NOT NULL auto_increment,
    PRIMARY KEY(CLASS_ID),
	CLASS_NAME VARCHAR(10) NOT NULL
)
auto_increment=3001;

INSERT INTO CLASSES(CLASS_NAME) VALUES('X DIV A');
INSERT INTO CLASSES(CLASS_NAME) VALUES('X DIV B');
INSERT INTO CLASSES(CLASS_NAME) VALUES('X DIV C');
INSERT INTO CLASSES(CLASS_NAME) VALUES('X DIV D');

CREATE TABLE STUDENTS
(
	STUD_ID int NOT NULL auto_increment,
    PRIMARY KEY(STUD_ID),
    CLASS_ID int,
	STUD_NAME VARCHAR(10) NOT NULL
)
auto_increment=4001;

INSERT INTO STUDENTS(STUD_NAME) VALUES('MAHESH');
INSERT INTO STUDENTS(STUD_NAME) VALUES('ROY');
INSERT INTO STUDENTS(STUD_NAME) VALUES('ROUNAK');
INSERT INTO STUDENTS(STUD_NAME) VALUES('KASHISH');
INSERT INTO STUDENTS(STUD_NAME) VALUES('DIMPLE');
INSERT INTO STUDENTS(STUD_NAME) VALUES('MAHENDRA');
INSERT INTO STUDENTS(STUD_NAME) VALUES('BOB');
INSERT INTO STUDENTS(STUD_NAME) VALUES('MARY');
INSERT INTO STUDENTS(STUD_NAME) VALUES('PARAG');
INSERT INTO STUDENTS(STUD_NAME) VALUES('DHANUSH');

CREATE TABLE CLASS_TEACH_SUB
(
	CTS_ID int NOT NULL auto_increment,
    PRIMARY KEY(CTS_ID),
    CLASS_ID int NOT NULL,
    TEACHER_ID int NOT NULL,
    SUB_ID VARCHAR(200) NOT NULL
)
auto_increment=5001;

CREATE TABLE USERS
(
	USER_ID int NOT NULL auto_increment,
    PRIMARY KEY(USER_ID),
	USER_NAME VARCHAR(20),
    USER_PASS VARCHAR(20),
    USER_ROLE VARCHAR(20)
)
auto_increment=6001;

INSERT INTO USERS(USER_NAME, USER_PASS, USER_ROLE) VALUES('admin', 'admin123', 'admin');

SELECT * FROM SUBJECTS;
SELECT * FROM TEACHERS;
SELECT * FROM CLASSES;
SELECT * FROM STUDENTS;
SELECT * FROM CLASS_TEACH_SUB;
SELECT * FROM USERS;